# Имя рабочего процесса, которое будет отображаться в GitHub Actions.
name: Build and Download Documentation

# Триггеры для запуска этого рабочего процесса.
on:
  # Позволяет запускать этот рабочий процесс вручную со страницы Actions.
  workflow_dispatch:

# Задачи, которые будут выполняться.
jobs:
  build:
    # Запускать на последней версии Ubuntu.
    runs-on: ubuntu-latest
    # Шаги, которые составляют задачу сборки.
    steps:
      # 1. Получение кода из репозитория.
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Настройка среды Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 3. Установка зависимостей в виртуальном окружении.
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install mkdocs-md-export-plugin
      
      # 4. Сборка документации с использованием специальной конфигурации.
      - name: Build documentation and export to Markdown
        run: |
          source venv/bin/activate
          mkdocs build --config-file mkdocs-build-docs.yml --strict --verbose

      # 5. Загрузка скомпилированных Markdown файлов как артефакта.
      - name: Upload Markdown artifact
        uses: actions/upload-artifact@v4
        with:
          # Имя артефакта, которое будет отображаться в GitHub.
          name: n8n-docs-markdown
          # Путь к директории с MD файлами, которую нужно загрузить.
          path: md_files
