# Имя рабочего процесса, которое будет отображаться в GitHub Actions.
name: Build and Download Documentation

# Триггеры для запуска этого рабочего процесса.
on:
  # Позволяет запускать этот рабочий процесс вручную со страницы Actions.
  workflow_dispatch:

# Задачи, которые будут выполняться.
jobs:
  build:
    # Запускать на последней версии Ubuntu.
    runs-on: ubuntu-latest
    # Шаги, которые составляют задачу сборки.
    steps:
      # 1. Получение кода из репозитория.
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Настройка среды Python версии 3.11.
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          # Кэширование зависимостей pip для ускорения последующих сборок.
          cache: 'pip'

      # 3. Установка зависимостей проекта.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Сборка сайта документации с помощью тестовой конфигурации.
      # Используем mkdocs-test.yml, чтобы избежать ошибок с платными плагинами.
      - name: Build documentation
        run: mkdocs build --config-file mkdocs-test.yml --strict --verbose

      # 5. Загрузка собранной документации как артефакта.
      # Это позволит скачать результат сборки со страницы выполнения рабочего процесса.
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          # Имя артефакта, которое будет отображаться в GitHub.
          name: n8n-docs-site
          # Путь к директории с собранным сайтом, которую нужно загрузить.
          path: site
